export const LOGIN_SUCCESS = 'LOGIN SUCCESSS'
export const LOGIN_FAIL = 'LOGIN FAILED'
export const LOGOUT = 'LOG OUT'

//NOTIFY
export const NOTIFY_DELETE_SUCCESSFULLY = 'DELETE SUCESSFULLY'
export const CLOSE_NOTIFY = 'CLOSE NOTIFY'
export const FORCE_LOG_OUT = 'FORCE LOG OUT'
export const NOTIFY_ERROR = 'NOTIFY ERROR'
export const NOTIFY_UPDATE_SUCCESSFULLY = 'NOTIFY UPDATE SUCCESSFULLY'
export const NOTIFY_CREATE_CONTEST_SUCCESSFULLY = 'NOTIFY CREATE CONTEST SUCCESSFULLY'
export const NOTIFY_SUCCESSFULLY= 'NOTIFY SUCCESSFULLY'



